/*
 * Generated by gdbus-codegen 2.48.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "ev-daemon-gdbus-generated.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.x.reader.Daemon
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:EvDaemon
 * @title: EvDaemon
 * @short_description: Generated C code for the org.x.reader.Daemon D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-x-reader-Daemon.top_of_page">org.x.reader.Daemon</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.x.reader.Daemon ---- */

static const _ExtendedGDBusArgInfo _ev_daemon_method_info_register_document_IN_ARG_uri =
{
  {
    -1,
    (gchar *) "uri",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ev_daemon_method_info_register_document_IN_ARG_pointers[] =
{
  &_ev_daemon_method_info_register_document_IN_ARG_uri,
  NULL
};

static const _ExtendedGDBusArgInfo _ev_daemon_method_info_register_document_OUT_ARG_owner =
{
  {
    -1,
    (gchar *) "owner",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ev_daemon_method_info_register_document_OUT_ARG_pointers[] =
{
  &_ev_daemon_method_info_register_document_OUT_ARG_owner,
  NULL
};

static const _ExtendedGDBusMethodInfo _ev_daemon_method_info_register_document =
{
  {
    -1,
    (gchar *) "RegisterDocument",
    (GDBusArgInfo **) &_ev_daemon_method_info_register_document_IN_ARG_pointers,
    (GDBusArgInfo **) &_ev_daemon_method_info_register_document_OUT_ARG_pointers,
    NULL
  },
  "handle-register-document",
  FALSE
};

static const _ExtendedGDBusArgInfo _ev_daemon_method_info_unregister_document_IN_ARG_uri =
{
  {
    -1,
    (gchar *) "uri",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ev_daemon_method_info_unregister_document_IN_ARG_pointers[] =
{
  &_ev_daemon_method_info_unregister_document_IN_ARG_uri,
  NULL
};

static const _ExtendedGDBusMethodInfo _ev_daemon_method_info_unregister_document =
{
  {
    -1,
    (gchar *) "UnregisterDocument",
    (GDBusArgInfo **) &_ev_daemon_method_info_unregister_document_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-unregister-document",
  FALSE
};

static const _ExtendedGDBusArgInfo _ev_daemon_method_info_find_document_IN_ARG_uri =
{
  {
    -1,
    (gchar *) "uri",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _ev_daemon_method_info_find_document_IN_ARG_spawn =
{
  {
    -1,
    (gchar *) "spawn",
    (gchar *) "b",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ev_daemon_method_info_find_document_IN_ARG_pointers[] =
{
  &_ev_daemon_method_info_find_document_IN_ARG_uri,
  &_ev_daemon_method_info_find_document_IN_ARG_spawn,
  NULL
};

static const _ExtendedGDBusArgInfo _ev_daemon_method_info_find_document_OUT_ARG_owner =
{
  {
    -1,
    (gchar *) "owner",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _ev_daemon_method_info_find_document_OUT_ARG_pointers[] =
{
  &_ev_daemon_method_info_find_document_OUT_ARG_owner,
  NULL
};

static const _ExtendedGDBusMethodInfo _ev_daemon_method_info_find_document =
{
  {
    -1,
    (gchar *) "FindDocument",
    (GDBusArgInfo **) &_ev_daemon_method_info_find_document_IN_ARG_pointers,
    (GDBusArgInfo **) &_ev_daemon_method_info_find_document_OUT_ARG_pointers,
    NULL
  },
  "handle-find-document",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _ev_daemon_method_info_pointers[] =
{
  &_ev_daemon_method_info_register_document,
  &_ev_daemon_method_info_unregister_document,
  &_ev_daemon_method_info_find_document,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _ev_daemon_interface_info =
{
  {
    -1,
    (gchar *) "org.x.reader.Daemon",
    (GDBusMethodInfo **) &_ev_daemon_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "daemon",
};


/**
 * ev_daemon_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-x-reader-Daemon.top_of_page">org.x.reader.Daemon</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
ev_daemon_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_ev_daemon_interface_info.parent_struct;
}

/**
 * ev_daemon_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #EvDaemon interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
ev_daemon_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * EvDaemon:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-x-reader-Daemon.top_of_page">org.x.reader.Daemon</link>.
 */

/**
 * EvDaemonIface:
 * @parent_iface: The parent interface.
 * @handle_find_document: Handler for the #EvDaemon::handle-find-document signal.
 * @handle_register_document: Handler for the #EvDaemon::handle-register-document signal.
 * @handle_unregister_document: Handler for the #EvDaemon::handle-unregister-document signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-x-reader-Daemon.top_of_page">org.x.reader.Daemon</link>.
 */

typedef EvDaemonIface EvDaemonInterface;
G_DEFINE_INTERFACE (EvDaemon, ev_daemon, G_TYPE_OBJECT);

static void
ev_daemon_default_init (EvDaemonIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * EvDaemon::handle-register-document:
   * @object: A #EvDaemon.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_uri: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-x-reader-Daemon.RegisterDocument">RegisterDocument()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call ev_daemon_complete_register_document() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-register-document",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EvDaemonIface, handle_register_document),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * EvDaemon::handle-unregister-document:
   * @object: A #EvDaemon.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_uri: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-x-reader-Daemon.UnregisterDocument">UnregisterDocument()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call ev_daemon_complete_unregister_document() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-unregister-document",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EvDaemonIface, handle_unregister_document),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * EvDaemon::handle-find-document:
   * @object: A #EvDaemon.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_uri: Argument passed by remote caller.
   * @arg_spawn: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-x-reader-Daemon.FindDocument">FindDocument()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call ev_daemon_complete_find_document() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-find-document",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (EvDaemonIface, handle_find_document),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    3,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING, G_TYPE_BOOLEAN);

}

/**
 * ev_daemon_call_register_document:
 * @proxy: A #EvDaemonProxy.
 * @arg_uri: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-x-reader-Daemon.RegisterDocument">RegisterDocument()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ev_daemon_call_register_document_finish() to get the result of the operation.
 *
 * See ev_daemon_call_register_document_sync() for the synchronous, blocking version of this method.
 */
void
ev_daemon_call_register_document (
    EvDaemon *proxy,
    const gchar *arg_uri,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "RegisterDocument",
    g_variant_new ("(s)",
                   arg_uri),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * ev_daemon_call_register_document_finish:
 * @proxy: A #EvDaemonProxy.
 * @out_owner: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_daemon_call_register_document().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with ev_daemon_call_register_document().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ev_daemon_call_register_document_finish (
    EvDaemon *proxy,
    gchar **out_owner,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_owner);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ev_daemon_call_register_document_sync:
 * @proxy: A #EvDaemonProxy.
 * @arg_uri: Argument to pass with the method invocation.
 * @out_owner: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-x-reader-Daemon.RegisterDocument">RegisterDocument()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See ev_daemon_call_register_document() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ev_daemon_call_register_document_sync (
    EvDaemon *proxy,
    const gchar *arg_uri,
    gchar **out_owner,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "RegisterDocument",
    g_variant_new ("(s)",
                   arg_uri),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_owner);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ev_daemon_call_unregister_document:
 * @proxy: A #EvDaemonProxy.
 * @arg_uri: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-x-reader-Daemon.UnregisterDocument">UnregisterDocument()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ev_daemon_call_unregister_document_finish() to get the result of the operation.
 *
 * See ev_daemon_call_unregister_document_sync() for the synchronous, blocking version of this method.
 */
void
ev_daemon_call_unregister_document (
    EvDaemon *proxy,
    const gchar *arg_uri,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "UnregisterDocument",
    g_variant_new ("(s)",
                   arg_uri),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * ev_daemon_call_unregister_document_finish:
 * @proxy: A #EvDaemonProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_daemon_call_unregister_document().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with ev_daemon_call_unregister_document().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ev_daemon_call_unregister_document_finish (
    EvDaemon *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ev_daemon_call_unregister_document_sync:
 * @proxy: A #EvDaemonProxy.
 * @arg_uri: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-x-reader-Daemon.UnregisterDocument">UnregisterDocument()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See ev_daemon_call_unregister_document() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ev_daemon_call_unregister_document_sync (
    EvDaemon *proxy,
    const gchar *arg_uri,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "UnregisterDocument",
    g_variant_new ("(s)",
                   arg_uri),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ev_daemon_call_find_document:
 * @proxy: A #EvDaemonProxy.
 * @arg_uri: Argument to pass with the method invocation.
 * @arg_spawn: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-x-reader-Daemon.FindDocument">FindDocument()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ev_daemon_call_find_document_finish() to get the result of the operation.
 *
 * See ev_daemon_call_find_document_sync() for the synchronous, blocking version of this method.
 */
void
ev_daemon_call_find_document (
    EvDaemon *proxy,
    const gchar *arg_uri,
    gboolean arg_spawn,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "FindDocument",
    g_variant_new ("(sb)",
                   arg_uri,
                   arg_spawn),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * ev_daemon_call_find_document_finish:
 * @proxy: A #EvDaemonProxy.
 * @out_owner: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_daemon_call_find_document().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with ev_daemon_call_find_document().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ev_daemon_call_find_document_finish (
    EvDaemon *proxy,
    gchar **out_owner,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_owner);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ev_daemon_call_find_document_sync:
 * @proxy: A #EvDaemonProxy.
 * @arg_uri: Argument to pass with the method invocation.
 * @arg_spawn: Argument to pass with the method invocation.
 * @out_owner: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-x-reader-Daemon.FindDocument">FindDocument()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See ev_daemon_call_find_document() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
ev_daemon_call_find_document_sync (
    EvDaemon *proxy,
    const gchar *arg_uri,
    gboolean arg_spawn,
    gchar **out_owner,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "FindDocument",
    g_variant_new ("(sb)",
                   arg_uri,
                   arg_spawn),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_owner);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * ev_daemon_complete_register_document:
 * @object: A #EvDaemon.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @owner: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-x-reader-Daemon.RegisterDocument">RegisterDocument()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
ev_daemon_complete_register_document (
    EvDaemon *object,
    GDBusMethodInvocation *invocation,
    const gchar *owner)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(s)",
                   owner));
}

/**
 * ev_daemon_complete_unregister_document:
 * @object: A #EvDaemon.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-x-reader-Daemon.UnregisterDocument">UnregisterDocument()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
ev_daemon_complete_unregister_document (
    EvDaemon *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * ev_daemon_complete_find_document:
 * @object: A #EvDaemon.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @owner: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-x-reader-Daemon.FindDocument">FindDocument()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
ev_daemon_complete_find_document (
    EvDaemon *object,
    GDBusMethodInvocation *invocation,
    const gchar *owner)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(s)",
                   owner));
}

/* ------------------------------------------------------------------------ */

/**
 * EvDaemonProxy:
 *
 * The #EvDaemonProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * EvDaemonProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #EvDaemonProxy.
 */

struct _EvDaemonProxyPrivate
{
  GData *qdata;
};

static void ev_daemon_proxy_iface_init (EvDaemonIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (EvDaemonProxy, ev_daemon_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (EvDaemonProxy)
                         G_IMPLEMENT_INTERFACE (EV_TYPE_DAEMON, ev_daemon_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (EvDaemonProxy, ev_daemon_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (EV_TYPE_DAEMON, ev_daemon_proxy_iface_init));

#endif
static void
ev_daemon_proxy_finalize (GObject *object)
{
  EvDaemonProxy *proxy = EV_DAEMON_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (ev_daemon_proxy_parent_class)->finalize (object);
}

static void
ev_daemon_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
ev_daemon_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
ev_daemon_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_ev_daemon_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], EV_TYPE_DAEMON);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, EV_TYPE_DAEMON);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
ev_daemon_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  EvDaemonProxy *proxy = EV_DAEMON_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_ev_daemon_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_ev_daemon_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
ev_daemon_proxy_init (EvDaemonProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = ev_daemon_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, EV_TYPE_DAEMON_PROXY, EvDaemonProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), ev_daemon_interface_info ());
}

static void
ev_daemon_proxy_class_init (EvDaemonProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = ev_daemon_proxy_finalize;
  gobject_class->get_property = ev_daemon_proxy_get_property;
  gobject_class->set_property = ev_daemon_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = ev_daemon_proxy_g_signal;
  proxy_class->g_properties_changed = ev_daemon_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (EvDaemonProxyPrivate));
#endif
}

static void
ev_daemon_proxy_iface_init (EvDaemonIface *iface)
{
}

/**
 * ev_daemon_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-x-reader-Daemon.top_of_page">org.x.reader.Daemon</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ev_daemon_proxy_new_finish() to get the result of the operation.
 *
 * See ev_daemon_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
ev_daemon_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (EV_TYPE_DAEMON_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.x.reader.Daemon", NULL);
}

/**
 * ev_daemon_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_daemon_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with ev_daemon_proxy_new().
 *
 * Returns: (transfer full) (type EvDaemonProxy): The constructed proxy object or %NULL if @error is set.
 */
EvDaemon *
ev_daemon_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return EV_DAEMON (ret);
  else
    return NULL;
}

/**
 * ev_daemon_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-x-reader-Daemon.top_of_page">org.x.reader.Daemon</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See ev_daemon_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type EvDaemonProxy): The constructed proxy object or %NULL if @error is set.
 */
EvDaemon *
ev_daemon_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (EV_TYPE_DAEMON_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.x.reader.Daemon", NULL);
  if (ret != NULL)
    return EV_DAEMON (ret);
  else
    return NULL;
}


/**
 * ev_daemon_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like ev_daemon_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ev_daemon_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See ev_daemon_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
ev_daemon_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (EV_TYPE_DAEMON_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.x.reader.Daemon", NULL);
}

/**
 * ev_daemon_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_daemon_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with ev_daemon_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type EvDaemonProxy): The constructed proxy object or %NULL if @error is set.
 */
EvDaemon *
ev_daemon_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return EV_DAEMON (ret);
  else
    return NULL;
}

/**
 * ev_daemon_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like ev_daemon_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See ev_daemon_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type EvDaemonProxy): The constructed proxy object or %NULL if @error is set.
 */
EvDaemon *
ev_daemon_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (EV_TYPE_DAEMON_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.x.reader.Daemon", NULL);
  if (ret != NULL)
    return EV_DAEMON (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * EvDaemonSkeleton:
 *
 * The #EvDaemonSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * EvDaemonSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #EvDaemonSkeleton.
 */

struct _EvDaemonSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_ev_daemon_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  EvDaemonSkeleton *skeleton = EV_DAEMON_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], EV_TYPE_DAEMON);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, EV_TYPE_DAEMON);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_ev_daemon_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  EvDaemonSkeleton *skeleton = EV_DAEMON_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_ev_daemon_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_ev_daemon_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  EvDaemonSkeleton *skeleton = EV_DAEMON_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_ev_daemon_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _ev_daemon_skeleton_vtable =
{
  _ev_daemon_skeleton_handle_method_call,
  _ev_daemon_skeleton_handle_get_property,
  _ev_daemon_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
ev_daemon_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return ev_daemon_interface_info ();
}

static GDBusInterfaceVTable *
ev_daemon_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_ev_daemon_skeleton_vtable;
}

static GVariant *
ev_daemon_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  EvDaemonSkeleton *skeleton = EV_DAEMON_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_ev_daemon_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _ev_daemon_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _ev_daemon_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _ev_daemon_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.x.reader.Daemon", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
ev_daemon_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void ev_daemon_skeleton_iface_init (EvDaemonIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (EvDaemonSkeleton, ev_daemon_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (EvDaemonSkeleton)
                         G_IMPLEMENT_INTERFACE (EV_TYPE_DAEMON, ev_daemon_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (EvDaemonSkeleton, ev_daemon_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (EV_TYPE_DAEMON, ev_daemon_skeleton_iface_init));

#endif
static void
ev_daemon_skeleton_finalize (GObject *object)
{
  EvDaemonSkeleton *skeleton = EV_DAEMON_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (ev_daemon_skeleton_parent_class)->finalize (object);
}

static void
ev_daemon_skeleton_init (EvDaemonSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = ev_daemon_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, EV_TYPE_DAEMON_SKELETON, EvDaemonSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
ev_daemon_skeleton_class_init (EvDaemonSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = ev_daemon_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = ev_daemon_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = ev_daemon_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = ev_daemon_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = ev_daemon_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (EvDaemonSkeletonPrivate));
#endif
}

static void
ev_daemon_skeleton_iface_init (EvDaemonIface *iface)
{
}

/**
 * ev_daemon_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-x-reader-Daemon.top_of_page">org.x.reader.Daemon</link>.
 *
 * Returns: (transfer full) (type EvDaemonSkeleton): The skeleton object.
 */
EvDaemon *
ev_daemon_skeleton_new (void)
{
  return EV_DAEMON (g_object_new (EV_TYPE_DAEMON_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for Object, ObjectProxy and ObjectSkeleton
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:EvObject
 * @title: EvObject
 * @short_description: Specialized GDBusObject types
 *
 * This section contains the #EvObject, #EvObjectProxy, and #EvObjectSkeleton types which make it easier to work with objects implementing generated types for D-Bus interfaces.
 */

/**
 * EvObject:
 *
 * The #EvObject type is a specialized container of interfaces.
 */

/**
 * EvObjectIface:
 * @parent_iface: The parent interface.
 *
 * Virtual table for the #EvObject interface.
 */

typedef EvObjectIface EvObjectInterface;
G_DEFINE_INTERFACE_WITH_CODE (EvObject, ev_object, G_TYPE_OBJECT, g_type_interface_add_prerequisite (g_define_type_id, G_TYPE_DBUS_OBJECT));

static void
ev_object_default_init (EvObjectIface *iface)
{
  /**
   * EvObject:daemon:
   *
   * The #EvDaemon instance corresponding to the D-Bus interface <link linkend="gdbus-interface-org-x-reader-Daemon.top_of_page">org.x.reader.Daemon</link>, if any.
   *
   * Connect to the #GObject::notify signal to get informed of property changes.
   */
  g_object_interface_install_property (iface, g_param_spec_object ("daemon", "daemon", "daemon", EV_TYPE_DAEMON, G_PARAM_READWRITE|G_PARAM_STATIC_STRINGS));

}

/**
 * ev_object_get_daemon:
 * @object: A #EvObject.
 *
 * Gets the #EvDaemon instance for the D-Bus interface <link linkend="gdbus-interface-org-x-reader-Daemon.top_of_page">org.x.reader.Daemon</link> on @object, if any.
 *
 * Returns: (transfer full): A #EvDaemon that must be freed with g_object_unref() or %NULL if @object does not implement the interface.
 */
EvDaemon *ev_object_get_daemon (EvObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.x.reader.Daemon");
  if (ret == NULL)
    return NULL;
  return EV_DAEMON (ret);
}


/**
 * ev_object_peek_daemon: (skip)
 * @object: A #EvObject.
 *
 * Like ev_object_get_daemon() but doesn't increase the reference count on the returned object.
 *
 * <warning>It is not safe to use the returned object if you are on another thread than the one where the #GDBusObjectManagerClient or #GDBusObjectManagerServer for @object is running.</warning>
 *
 * Returns: (transfer none): A #EvDaemon or %NULL if @object does not implement the interface. Do not free the returned object, it is owned by @object.
 */
EvDaemon *ev_object_peek_daemon (EvObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.x.reader.Daemon");
  if (ret == NULL)
    return NULL;
  g_object_unref (ret);
  return EV_DAEMON (ret);
}


static void
ev_object_notify (GDBusObject *object, GDBusInterface *interface)
{
  _ExtendedGDBusInterfaceInfo *info = (_ExtendedGDBusInterfaceInfo *) g_dbus_interface_get_info (interface);
  /* info can be NULL if the other end is using a D-Bus interface we don't know
   * anything about, for example old generated code in this process talking to
   * newer generated code in the other process. */
  if (info != NULL)
    g_object_notify (G_OBJECT (object), info->hyphen_name);
}

/**
 * EvObjectProxy:
 *
 * The #EvObjectProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * EvObjectProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #EvObjectProxy.
 */

static void
ev_object_proxy__ev_object_iface_init (EvObjectIface *iface G_GNUC_UNUSED)
{
}

static void
ev_object_proxy__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = ev_object_notify;
  iface->interface_removed = ev_object_notify;
}


G_DEFINE_TYPE_WITH_CODE (EvObjectProxy, ev_object_proxy, G_TYPE_DBUS_OBJECT_PROXY,
                         G_IMPLEMENT_INTERFACE (EV_TYPE_OBJECT, ev_object_proxy__ev_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, ev_object_proxy__g_dbus_object_iface_init));

static void
ev_object_proxy_init (EvObjectProxy *object G_GNUC_UNUSED)
{
}

static void
ev_object_proxy_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value G_GNUC_UNUSED,
  GParamSpec   *pspec)
{
  G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
}

static void
ev_object_proxy_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  EvObjectProxy *object = EV_OBJECT_PROXY (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.x.reader.Daemon");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
ev_object_proxy_class_init (EvObjectProxyClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = ev_object_proxy_set_property;
  gobject_class->get_property = ev_object_proxy_get_property;

  g_object_class_override_property (gobject_class, 1, "daemon");
}

/**
 * ev_object_proxy_new:
 * @connection: A #GDBusConnection.
 * @object_path: An object path.
 *
 * Creates a new proxy object.
 *
 * Returns: (transfer full): The proxy object.
 */
EvObjectProxy *
ev_object_proxy_new (GDBusConnection *connection,
  const gchar *object_path)
{
  g_return_val_if_fail (G_IS_DBUS_CONNECTION (connection), NULL);
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return EV_OBJECT_PROXY (g_object_new (EV_TYPE_OBJECT_PROXY, "g-connection", connection, "g-object-path", object_path, NULL));
}

/**
 * EvObjectSkeleton:
 *
 * The #EvObjectSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * EvObjectSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #EvObjectSkeleton.
 */

static void
ev_object_skeleton__ev_object_iface_init (EvObjectIface *iface G_GNUC_UNUSED)
{
}


static void
ev_object_skeleton__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = ev_object_notify;
  iface->interface_removed = ev_object_notify;
}

G_DEFINE_TYPE_WITH_CODE (EvObjectSkeleton, ev_object_skeleton, G_TYPE_DBUS_OBJECT_SKELETON,
                         G_IMPLEMENT_INTERFACE (EV_TYPE_OBJECT, ev_object_skeleton__ev_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, ev_object_skeleton__g_dbus_object_iface_init));

static void
ev_object_skeleton_init (EvObjectSkeleton *object G_GNUC_UNUSED)
{
}

static void
ev_object_skeleton_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  EvObjectSkeleton *object = EV_OBJECT_SKELETON (gobject);
  GDBusInterfaceSkeleton *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_value_get_object (value);
      if (interface != NULL)
        {
          g_warn_if_fail (EV_IS_DAEMON (interface));
          g_dbus_object_skeleton_add_interface (G_DBUS_OBJECT_SKELETON (object), interface);
        }
      else
        {
          g_dbus_object_skeleton_remove_interface_by_name (G_DBUS_OBJECT_SKELETON (object), "org.x.reader.Daemon");
        }
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
ev_object_skeleton_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  EvObjectSkeleton *object = EV_OBJECT_SKELETON (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.x.reader.Daemon");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
ev_object_skeleton_class_init (EvObjectSkeletonClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = ev_object_skeleton_set_property;
  gobject_class->get_property = ev_object_skeleton_get_property;

  g_object_class_override_property (gobject_class, 1, "daemon");
}

/**
 * ev_object_skeleton_new:
 * @object_path: An object path.
 *
 * Creates a new skeleton object.
 *
 * Returns: (transfer full): The skeleton object.
 */
EvObjectSkeleton *
ev_object_skeleton_new (const gchar *object_path)
{
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return EV_OBJECT_SKELETON (g_object_new (EV_TYPE_OBJECT_SKELETON, "g-object-path", object_path, NULL));
}

/**
 * ev_object_skeleton_set_daemon:
 * @object: A #EvObjectSkeleton.
 * @interface_: (allow-none): A #EvDaemon or %NULL to clear the interface.
 *
 * Sets the #EvDaemon instance for the D-Bus interface <link linkend="gdbus-interface-org-x-reader-Daemon.top_of_page">org.x.reader.Daemon</link> on @object.
 */
void ev_object_skeleton_set_daemon (EvObjectSkeleton *object, EvDaemon *interface_)
{
  g_object_set (G_OBJECT (object), "daemon", interface_, NULL);
}


/* ------------------------------------------------------------------------
 * Code for ObjectManager client
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:EvObjectManagerClient
 * @title: EvObjectManagerClient
 * @short_description: Generated GDBusObjectManagerClient type
 *
 * This section contains a #GDBusObjectManagerClient that uses ev_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc.
 */

/**
 * EvObjectManagerClient:
 *
 * The #EvObjectManagerClient structure contains only private data and should only be accessed using the provided API.
 */

/**
 * EvObjectManagerClientClass:
 * @parent_class: The parent class.
 *
 * Class structure for #EvObjectManagerClient.
 */

G_DEFINE_TYPE (EvObjectManagerClient, ev_object_manager_client, G_TYPE_DBUS_OBJECT_MANAGER_CLIENT);

static void
ev_object_manager_client_init (EvObjectManagerClient *manager G_GNUC_UNUSED)
{
}

static void
ev_object_manager_client_class_init (EvObjectManagerClientClass *klass G_GNUC_UNUSED)
{
}

/**
 * ev_object_manager_client_get_proxy_type:
 * @manager: A #GDBusObjectManagerClient.
 * @object_path: The object path of the remote object (unused).
 * @interface_name: (allow-none): Interface name of the remote object or %NULL to get the object proxy #GType.
 * @user_data: User data (unused).
 *
 * A #GDBusProxyTypeFunc that maps @interface_name to the generated #GDBusObjectProxy<!-- -->- and #GDBusProxy<!-- -->-derived types.
 *
 * Returns: A #GDBusProxy<!-- -->-derived #GType if @interface_name is not %NULL, otherwise the #GType for #EvObjectProxy.
 */
GType
ev_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager G_GNUC_UNUSED, const gchar *object_path G_GNUC_UNUSED, const gchar *interface_name, gpointer user_data G_GNUC_UNUSED)
{
  static gsize once_init_value = 0;
  static GHashTable *lookup_hash;
  GType ret;

  if (interface_name == NULL)
    return EV_TYPE_OBJECT_PROXY;
  if (g_once_init_enter (&once_init_value))
    {
      lookup_hash = g_hash_table_new (g_str_hash, g_str_equal);
      g_hash_table_insert (lookup_hash, (gpointer) "org.x.reader.Daemon", GSIZE_TO_POINTER (EV_TYPE_DAEMON_PROXY));
      g_once_init_leave (&once_init_value, 1);
    }
  ret = (GType) GPOINTER_TO_SIZE (g_hash_table_lookup (lookup_hash, interface_name));
  if (ret == (GType) 0)
    ret = G_TYPE_DBUS_PROXY;
  return ret;
}

/**
 * ev_object_manager_client_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates #GDBusObjectManagerClient using ev_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ev_object_manager_client_new_finish() to get the result of the operation.
 *
 * See ev_object_manager_client_new_sync() for the synchronous, blocking version of this constructor.
 */
void
ev_object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (EV_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", ev_object_manager_client_get_proxy_type, NULL);
}

/**
 * ev_object_manager_client_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_object_manager_client_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with ev_object_manager_client_new().
 *
 * Returns: (transfer full) (type EvObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
ev_object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * ev_object_manager_client_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates #GDBusObjectManagerClient using ev_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See ev_object_manager_client_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type EvObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
ev_object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (EV_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", ev_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


/**
 * ev_object_manager_client_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like ev_object_manager_client_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call ev_object_manager_client_new_for_bus_finish() to get the result of the operation.
 *
 * See ev_object_manager_client_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
ev_object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (EV_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", ev_object_manager_client_get_proxy_type, NULL);
}

/**
 * ev_object_manager_client_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to ev_object_manager_client_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with ev_object_manager_client_new_for_bus().
 *
 * Returns: (transfer full) (type EvObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
ev_object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * ev_object_manager_client_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like ev_object_manager_client_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See ev_object_manager_client_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type EvObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
ev_object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (EV_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", ev_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


