.TH atril\-previewer 1 2007\-01\-15  
.SH NAME
atril\-previewer \- show print preview for a document
.SH SYNOPSIS
\fBatril\-previewer\fR \fB[file]\fR 
.SH DESCRIPTION
atril\-previewer is a MATE program to
show print preview dialog for files supported by atril.
.SH OPTIONS
atril\-previewer obeys all normal GTK+ 
command line options.
.SH "SEE ALSO"
\fBatril\fR(1),
\fBgtk\-options\fR(7).
.PP
http://www.mate-desktop.org/
