.TH xreader\-previewer 1 2007\-01\-15  
.SH NAME
xreader\-previewer \- show print preview for a document
.SH SYNOPSIS
\fBxreader\-previewer\fR \fB[file]\fR 
.SH DESCRIPTION
xreader\-previewer is a program to
show print preview dialog for files supported by xreader.
.SH OPTIONS
xreader\-previewer obeys all normal GTK+ 
command line options.
.SH "SEE ALSO"
\fBxreader\fR(1),
\fBgtk\-options\fR(7).
.PP
https://www.github.com/linuxmint/xreader/
