.TH atril\-thumbnailer 1 2007\-01\-15  
.SH NAME
atril\-thumbnailer \- create png thumbnails from atril supported documents
.SH SYNOPSIS
\fBatril\-thumbnailer\fR [\-s \fBsize\fR] \fBinput\fR \fBoutput\fR 
.SH DESCRIPTION
atril\-thumbnailer is a MATE program to
create thumbnails from files supported by atril.
.SH OPTIONS
atril\-thumbnailer obeys all normal GTK+ 
command line options. The only option \-s \fIsize
\fRmakes it possible to choose the vertical size
of the created thumbnail.
.SH "SEE ALSO"
\fBatril\fR(1),
\fBgtk\-options\fR(7).
.PP
http://www.mate-desktop.org//
