.TH xreader\-thumbnailer 1 2007\-01\-15  
.SH NAME
xreader\-thumbnailer \- create png thumbnails from xreader supported documents
.SH SYNOPSIS
\fBxreader\-thumbnailer\fR [\-s \fBsize\fR] \fBinput\fR \fBoutput\fR 
.SH DESCRIPTION
xreader\-thumbnailer is a MATE program to
create thumbnails from files supported by xreader.
.SH OPTIONS
xreader\-thumbnailer obeys all normal GTK+ 
command line options. The only option \-s \fIsize
\fRmakes it possible to choose the vertical size
of the created thumbnail.
.SH "SEE ALSO"
\fBxreader\fR(1),
\fBgtk\-options\fR(7).
.PP
http://www.mate-desktop.org//
